### ISSUE TITLE
Arrow keys don't work

### ISSUE THREAD

**Issue by pozitron57** [hombit/olgart#2]
At the bottom of the each painting ([example](https://olgart.ru/galleries/flowers/irises/#view)) it is written that one may use arrow keys to leaf through the paintings. But this feature actually doesn't work (I use OS Ubuntu 14.10 and Chrome Version 47.0.2526.73 (64-bit)

**Comment by hombit** [comment]
Thank you! It was wrong order of including js libraries.
Fixed by [last commit](https://github.com/hombit/olgart/commit/c7a846f5e2b456099197db0e6530fc1954dd918e)

**Comment by pozitron57** [comment]
Awesome! Thanks
